version: '3'

services:
  redis:
    image: redis:latest
    ports:
      - "6380:6379"

  postgres:
    image: postgres:latest
    ports:
      - "5433:5432"
   
    environment:
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
   

